apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tshering-deploy
  name: tshering-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tshering-deploy
  template:
    metadata:
      labels:
        app: pet-deploy
    spec:
      containers:
      - image: tyangden/cat:latest
        name: pet
